name: tienda_tech
description: Tienda de tecnología en Flutter
publish_to: "none"
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  dio: ^5.0.0
  freezed_annotation: ^2.0.0
  json_annotation: ^4.8.0
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.1
  flutter_stripe: ^9.0.0 # revisar versión y requisitos de native
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  freezed: ^2.3.2
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/